version: "2.3"
services:
  socat:
    image: alpine/socat:latest
    depends_on:
      - vpn
    command: ["tcp4-listen:3210,reuseaddr,fork", "tcp:${FORTI_SOCAT_DEST_ADDR}:${FORTI_SOCAT_DEST_PORT}"]
    healthcheck:
      test: [ "CMD-SHELL", "test `ip -o a show | cut -d ' ' -f 2 | grep ppp0 | wc -l` -eq 1 || kill 1" ]
      interval: 11s
      timeout: 2s
    restart: "always"
    network_mode: "service:vpn"
    logging:
      driver: ${VPN_LOG_DRIVER:-json-file}
      options:
        max-size: ${VPN_LOG_MAX_SIZE:-2m}
        max-file: ${VPN_LOG_MAX_FILE:-10}
